### ISSUE TITLE
Setup File

### ISSUE THREAD

**Issue by VFXGamer** [dhhruv/EncrypC#1]
Adding a setup file would make it easy for others to use the program.
You can assign this issue to me.

**Comment by dhhruv** [comment]
I have already added the .exe file under Releases for easy usage of the program. Can you elaborate how this setup will be useful ??

**Comment by VFXGamer** [comment]
It will be useful to dev who want to contribute to the project.

**Comment by dhhruv** [comment]
Yeah, you are right. I'm assigning the issue to you.
